//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShop.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;initial catalog=ShopDB;integrated security=True;MultipleActiveResul" +
            "tSets=True;App=EntityFramework&quot;")]
        public string ConnectionString {
            get {
                return ((string)(this["ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("farhadsender1367@gmail.com")]
        public string emailSender {
            get {
                return ((string)(this["emailSender"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("farhadsender1367")]
        public string emailUsername {
            get {
                return ((string)(this["emailUsername"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Fe23565!@#")]
        public string emailPassword {
            get {
                return ((string)(this["emailPassword"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("data source=37.156.146.197,1496;initial catalog=wikisaat_shop;User ID=wikisaatSho" +
            "pPdUser;Password=S2_3k-3gy8WSxCf;MultipleActiveResultSets=True;App=EntityFramewo" +
            "rk&quot;")]
        public string ServerConnectionString {
            get {
                return ((string)(this["ServerConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"
<RSAKeyValue><Modulus>qw2AyhQoa1QsCBjODBy74pySnhXhKFojm520Z+3ozto3HRHvJjdNYwlhjUl7KtzQLoLJ9lHDUszL5BJVpHYV8QXF95M9PN4bQgXdVqrEoyMGjUpRv4K/JE8N5m0lJoTVozwt+C0Icqgidx40MSdCO6QxVuE9DTplELjl8M1a08W2LZf/B+NvbGetUQhOQKT+Vd6cQnpCNi71Gcl+LOYcdr17g2bAB2SStu/ua2o34pdyoF+bmk4oRohfEeTh4ZT7DSVJumNjDGLxzpyLUF8wdjXuvDDky8M2Kka3gOv0rvunxn+EnXgkEi2h5TR0MfeugMkc1gdIRkldhZ642+OEJQ==</Modulus><Exponent>AQAB</Exponent></RSAKeyValue>

<RSAKeyValue><Modulus>qw2AyhQoa1QsCBjODBy74pySnhXhKFojm520Z+3ozto3HRHvJjdNYwlhjUl7KtzQLoLJ9lHDUszL5BJVpHYV8QXF95M9PN4bQgXdVqrEoyMGjUpRv4K/JE8N5m0lJoTVozwt+C0Icqgidx40MSdCO6QxVuE9DTplELjl8M1a08W2LZf/B+NvbGetUQhOQKT+Vd6cQnpCNi71Gcl+LOYcdr17g2bAB2SStu/ua2o34pdyoF+bmk4oRohfEeTh4ZT7DSVJumNjDGLxzpyLUF8wdjXuvDDky8M2Kka3gOv0rvunxn+EnXgkEi2h5TR0MfeugMkc1gdIRkldhZ642+OEJQ==</Modulus><Exponent>AQAB</Exponent></RSAKeyValue>
")]
        public string PublicKey {
            get {
                return ((string)(this["PublicKey"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\r\n<RSAKeyValue><Modulus>qw2AyhQoa1QsCBjODBy74pySnhXhKFojm520Z+3ozto3HRHvJjdNYwlhj" +
            "Ul7KtzQLoLJ9lHDUszL5BJVpHYV8QXF95M9PN4bQgXdVqrEoyMGjUpRv4K/JE8N5m0lJoTVozwt+C0Ic" +
            "qgidx40MSdCO6QxVuE9DTplELjl8M1a08W2LZf/B+NvbGetUQhOQKT+Vd6cQnpCNi71Gcl+LOYcdr17g" +
            "2bAB2SStu/ua2o34pdyoF+bmk4oRohfEeTh4ZT7DSVJumNjDGLxzpyLUF8wdjXuvDDky8M2Kka3gOv0r" +
            "vunxn+EnXgkEi2h5TR0MfeugMkc1gdIRkldhZ642+OEJQ==</Modulus><Exponent>AQAB</Exponen" +
            "t><P>4Aojh9IQqoQUkv4oWEC1rxeik2IyUiVJf/MIVDsYkG/WScUdaoVaLyWm3DwzidSC6LPkzXBVJFb" +
            "jI4GCr5IdPfQGdXbbf0k7DrtY8bA9Nh5ca1n73P0o+emyiWEY+Led3kQRr8+BZzzlMl7WUNLAos5TuOF" +
            "98mEvltJJAX9Elc8=</P><Q>w3RMtR/dhjK8Wn2dfmZeiHKgekivDgmzlCxWWMJvtEPfBs0tJIXeDTK3" +
            "9ZNyE/a9EgOu0J3YRXQmW7e/1vPhFkCauS0YCmrbfWKknoD/it+cbvVSBdVKhkvPrNkYzraet+QYCrA0" +
            "eK4uwyJsSkxFsLqQ85YQ2ty99GM8K9Aq98s=</Q><DP>ENfSSgC57gfWACMJZ3Ed95bgSxJD1Dcnam4b" +
            "/zEeLKWrx4oBJyP1XrwG6mHAQilu2g3EMsmyLPQ3SVEQQSDL//9biPMxl0UrInVlP25Pe8UWj5+JNtj1" +
            "fqxaFsfs963eOXqGleAUy20hkgLdO+BMSTEXzDtvm4xA5qbShEFMJ7M=</DP><DQ>rs0wXTymbgKqGXQ" +
            "GiqkbGoUJqNOgW7mpdXdBshgStvGMYRTWrrdapAscIvE/MUOWTKomikTgyxzZwWVQmPl78N7OgZYmzgp" +
            "LSpQSDf/oi1b5HPMh7D2ZbQoYLcnrOdRxlpzUM5rrEpMVF0eN+dTE7w2r3W30nQiWih7GDZkbFIk=</D" +
            "Q><InverseQ>NeguRtpJmvS+LxXopqhAv3vdonQJ94oesEgC13t6sFAersxybG/Le2wc8ZnTPH7Jpkfs" +
            "R7WBlhNgkBaBKxRbgQWAigXIrUb2p+My/uSqvzY4kRoesPaf+SDUrHiC00DaV73BopgtIxaKKw9Am6jj" +
            "do3eIehz1cg8hKYaHywLeFc=</InverseQ><D>aQOaPPYRNotvmOz5mxAM/XwYu3s9R1PHpqM0fdXe5x" +
            "erXGqFQxYSqam5vU8OkesM2HEtYs8htnTK/FORRq3EnLtppaw8nWDSpT8Ke0nN/UXkoNuuwn+Xr8flBc" +
            "GeXD6TFms84a9sD1BQEId3jXHHxOvx6p/Ppo5iO9j4OlUo3Pf0bJphGq/89uj9DwWGfb4XfisbaNDQe5" +
            "BQygzILmdTroYWLv6ayEbEI7y9LpiN7aSilkaee+giaZkj/lD2+4zLFAROyQCUFBSbHcsM6zlt7Ai7wH" +
            "nB3XjlgccegviMDcMAIxASTSDWTJcDcjypg2qv6Z7Sqf0Xs7MDtG9qcClFhQ==</D></RSAKeyValue>" +
            "")]
        public string PrivateKey {
            get {
                return ((string)(this["PrivateKey"]));
            }
        }
    }
}
