//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Banner
    {
        public int id { get; set; }
        public string banner1 { get; set; }
        public string banner2 { get; set; }
        public string banner3 { get; set; }
        public string banner4 { get; set; }
        public string banner5 { get; set; }
        public string banner6 { get; set; }
        public string banner7 { get; set; }
        public string banner8 { get; set; }
        public string link1 { get; set; }
        public string link2 { get; set; }
        public string link3 { get; set; }
        public string link4 { get; set; }
        public string link5 { get; set; }
        public string link6 { get; set; }
        public string link7 { get; set; }
        public string link8 { get; set; }
        public Nullable<bool> active { get; set; }
        public string title { get; set; }
        public string banner9 { get; set; }
        public string link9 { get; set; }
        public string banner10 { get; set; }
        public string link10 { get; set; }
        public string banner11 { get; set; }
        public string link11 { get; set; }
        public string banner12 { get; set; }
        public string link12 { get; set; }
        public string banner13 { get; set; }
        public string link13 { get; set; }
        public string banner14 { get; set; }
        public string link14 { get; set; }
        public string banner15 { get; set; }
        public string link15 { get; set; }
    }
}
