//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Basket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Basket()
        {
            this.DiscountCodes = new HashSet<DiscountCode>();
            this.Orders = new HashSet<Order>();
            this.Scans = new HashSet<Scan>();
            this.WalletPays = new HashSet<WalletPay>();
        }
    
        public int id { get; set; }
        public Nullable<int> userId { get; set; }
        public Nullable<System.DateTime> creationDate { get; set; }
        public string payMethod { get; set; }
        public Nullable<bool> payed { get; set; }
        public Nullable<long> Price { get; set; }
        public string status { get; set; }
        public string token { get; set; }
        public string address { get; set; }
        public string post { get; set; }
        public Nullable<System.DateTime> sendReserveTime { get; set; }
        public Nullable<int> sendReservePeriod { get; set; }
        public string periodString { get; set; }
        public Nullable<long> shippingPrice { get; set; }
        public Nullable<int> DiscountCode { get; set; }
        public Nullable<long> DiscountAmount { get; set; }
        public Nullable<int> addressId { get; set; }
        public string authority { get; set; }
        public Nullable<bool> invoicing { get; set; }
        public Nullable<int> ShippingId { get; set; }
        public string wizardStatus { get; set; }
    
        public virtual DiscountCode DiscountCode1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DiscountCode> DiscountCodes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Scan> Scans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WalletPay> WalletPays { get; set; }
    }
}
