//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Category()
        {
            this.CatProes = new HashSet<CatPro>();
            this.CatProperties = new HashSet<CatProperty>();
            this.Seller_cats = new HashSet<Seller_cats>();
        }
    
        public int id { get; set; }
        public string title { get; set; }
        public string banner { get; set; }
        public string RightBanner { get; set; }
        public string HomePhoto { get; set; }
        public Nullable<int> MainCat { get; set; }
        public string Img { get; set; }
        public Nullable<int> parent { get; set; }
        public Nullable<int> Adv { get; set; }
        public Nullable<int> line1Ads { get; set; }
        public Nullable<int> line2Ads { get; set; }
        public Nullable<int> line3Ads { get; set; }
        public Nullable<bool> showInHomePage { get; set; }
        public Nullable<int> priority { get; set; }
        public string Description { get; set; }
        public string Icon { get; set; }
    
        public virtual MainCat MainCat1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatPro> CatProes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatProperty> CatProperties { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Seller_cats> Seller_cats { get; set; }
    }
}
