//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Comment()
        {
            this.CommentAdvantages = new HashSet<CommentAdvantage>();
            this.CommnetsLikes = new HashSet<CommnetsLike>();
            this.RattingComments = new HashSet<RattingComment>();
        }
    
        public int id { get; set; }
        public string text { get; set; }
        public Nullable<int> rate { get; set; }
        public Nullable<int> productId { get; set; }
        public Nullable<int> userid { get; set; }
        public Nullable<System.DateTime> creationDate { get; set; }
        public Nullable<bool> show { get; set; }
        public string guestName { get; set; }
        public string title { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommentAdvantage> CommentAdvantages { get; set; }
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommnetsLike> CommnetsLikes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RattingComment> RattingComments { get; set; }
    }
}
