//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiscountGroup
    {
        public int id { get; set; }
        public string Name { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<long> Amount { get; set; }
        public Nullable<int> Percentage { get; set; }
        public Nullable<long> maxPercentage { get; set; }
    }
}
