//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiscountCode
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DiscountCode()
        {
            this.Baskets = new HashSet<Basket>();
        }
    
        public int id { get; set; }
        public string code { get; set; }
        public Nullable<System.DateTime> creationDate { get; set; }
        public Nullable<System.DateTime> useDate { get; set; }
        public Nullable<long> Amont { get; set; }
        public Nullable<int> basketId { get; set; }
        public Nullable<bool> isUsed { get; set; }
        public Nullable<int> GroupId { get; set; }
        public Nullable<long> Percentage { get; set; }
        public Nullable<long> maxPercentage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Basket> Baskets { get; set; }
        public virtual Basket Basket { get; set; }
    }
}
