//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Footer
    {
        public int id { get; set; }
        public string f1Header { get; set; }
        public string f1r1 { get; set; }
        public string f1r1_Link { get; set; }
        public string f1r2 { get; set; }
        public string f1r2_Link { get; set; }
        public string f1r3 { get; set; }
        public string f1r3_Link { get; set; }
        public string f1r4 { get; set; }
        public string f1r4_Link { get; set; }
        public string f1r5 { get; set; }
        public string f1r5_Link { get; set; }
        public string f1r6 { get; set; }
        public string f1r6_Link { get; set; }
        public string f1r7 { get; set; }
        public string f1r7_Link { get; set; }
        public string f2Header { get; set; }
        public string f2r1 { get; set; }
        public string f2r1_Link { get; set; }
        public string f2r2 { get; set; }
        public string f2r2_Link { get; set; }
        public string f2r3 { get; set; }
        public string f2r3_Link { get; set; }
        public string f2r4 { get; set; }
        public string f2r4_Link { get; set; }
        public string f2r5 { get; set; }
        public string f2r5_Link { get; set; }
        public string f2r6 { get; set; }
        public string f2r6_Link { get; set; }
        public string f2r7 { get; set; }
        public string f2r7_Link { get; set; }
        public string f3Header { get; set; }
        public string f3r1 { get; set; }
        public string f3r1_Link { get; set; }
        public string f3r2 { get; set; }
        public string f3r2_Link { get; set; }
        public string f3r3 { get; set; }
        public string f3r3_Link { get; set; }
        public string f3r4 { get; set; }
        public string f3r4_Link { get; set; }
        public string f3r5 { get; set; }
        public string f3r5_Link { get; set; }
        public string f3r6 { get; set; }
        public string f3r6_Link { get; set; }
        public string f3r7 { get; set; }
        public string f3r7_Link { get; set; }
        public string f4Header { get; set; }
        public string f4r1 { get; set; }
        public string f4r1_Link { get; set; }
        public string f4r2 { get; set; }
        public string f4r2_Link { get; set; }
        public string f4r3 { get; set; }
        public string f4r3_Link { get; set; }
        public string f4r4 { get; set; }
        public string f4r4_Link { get; set; }
        public string f4r5 { get; set; }
        public string f4r5_Link { get; set; }
        public string f4r6 { get; set; }
        public string f4r6_Link { get; set; }
        public string f4r7 { get; set; }
        public string f4r7_Link { get; set; }
    }
}
