//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gift
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Gift()
        {
            this.GiftOrders = new HashSet<GiftOrder>();
        }
    
        public int id { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public Nullable<long> price { get; set; }
        public string short_description { get; set; }
        public Nullable<bool> isAvailable { get; set; }
        public Nullable<bool> isValid { get; set; }
        public Nullable<System.DateTime> creationDate { get; set; }
        public string MainImage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GiftOrder> GiftOrders { get; set; }
    }
}
