//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogPassword
    {
        public int LogPasswordId { get; set; }
        public int UserId { get; set; }
        public string Pass { get; set; }
    
        public virtual User User { get; set; }
    }
}
