//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogUserAuthenticationData
    {
        public int id { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string UserName { get; set; }
        public byte AuthenticationLogType { get; set; }
        public string IP { get; set; }
        public string Hostname { get; set; }
        public string Description { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual User User { get; set; }
    }
}
