//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogUserData
    {
        public System.DateTime CreateDate { get; set; }
        public string UserName { get; set; }
        public string Type { get; set; }
        public string ControllerName { get; set; }
        public string ActionName { get; set; }
        public string AreaName { get; set; }
        public int LogUserDataId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string IP { get; set; }
        public string Hostname { get; set; }
    
        public virtual User User { get; set; }
    }
}
