//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShop.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OnlineShopEntities : DbContext
    {
        public OnlineShopEntities()
            : base("name=OnlineShopEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminUser> AdminUsers { get; set; }
        public virtual DbSet<AllowedIpAddress> AllowedIpAddresses { get; set; }
        public virtual DbSet<Banner> Banners { get; set; }
        public virtual DbSet<Basket> Baskets { get; set; }
        public virtual DbSet<Blog_Cats> Blog_Cats { get; set; }
        public virtual DbSet<Blog_Comments> Blog_Comments { get; set; }
        public virtual DbSet<Blog_post> Blog_post { get; set; }
        public virtual DbSet<Blog_Tags> Blog_Tags { get; set; }
        public virtual DbSet<Blog_TagsPosts> Blog_TagsPosts { get; set; }
        public virtual DbSet<Brand> Brands { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<CatPro> CatProes { get; set; }
        public virtual DbSet<CatProperty> CatProperties { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Color> Colors { get; set; }
        public virtual DbSet<ColorSize> ColorSizes { get; set; }
        public virtual DbSet<CommentAdvantage> CommentAdvantages { get; set; }
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<CommnetsLike> CommnetsLikes { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<ContactInformation> ContactInformations { get; set; }
        public virtual DbSet<Discount> Discounts { get; set; }
        public virtual DbSet<DiscountCode> DiscountCodes { get; set; }
        public virtual DbSet<DiscountGroup> DiscountGroups { get; set; }
        public virtual DbSet<FalsePassword> FalsePasswords { get; set; }
        public virtual DbSet<Faq> Faqs { get; set; }
        public virtual DbSet<FaqCategory> FaqCategories { get; set; }
        public virtual DbSet<Footer> Footers { get; set; }
        public virtual DbSet<GeomaticCategory> GeomaticCategories { get; set; }
        public virtual DbSet<GiftOrder> GiftOrders { get; set; }
        public virtual DbSet<Gift> Gifts { get; set; }
        public virtual DbSet<Log> Logs { get; set; }
        public virtual DbSet<LogPassword> LogPasswords { get; set; }
        public virtual DbSet<LogUserAuthenticationData> LogUserAuthenticationDatas { get; set; }
        public virtual DbSet<LogUserData> LogUserDatas { get; set; }
        public virtual DbSet<MainCat> MainCats { get; set; }
        public virtual DbSet<Menu> Menus { get; set; }
        public virtual DbSet<Model> Models { get; set; }
        public virtual DbSet<newsLetter> newsLetters { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Page> Pages { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<Permission> Permissions { get; set; }
        public virtual DbSet<ProductGallery> ProductGalleries { get; set; }
        public virtual DbSet<ProductPropertiesValue> ProductPropertiesValues { get; set; }
        public virtual DbSet<ProductQAnswer> ProductQAnswers { get; set; }
        public virtual DbSet<ProductQuestion> ProductQuestions { get; set; }
        public virtual DbSet<ProductRating> ProductRatings { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<ProductsBrand> ProductsBrands { get; set; }
        public virtual DbSet<ProductTag> ProductTags { get; set; }
        public virtual DbSet<productView> productViews { get; set; }
        public virtual DbSet<Promotion> Promotions { get; set; }
        public virtual DbSet<propertiesCategory> propertiesCategories { get; set; }
        public virtual DbSet<Rating> Ratings { get; set; }
        public virtual DbSet<RatingGroup> RatingGroups { get; set; }
        public virtual DbSet<RattingComment> RattingComments { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Scan> Scans { get; set; }
        public virtual DbSet<Seller_cats> Seller_cats { get; set; }
        public virtual DbSet<SellerComment> SellerComments { get; set; }
        public virtual DbSet<Seller> Sellers { get; set; }
        public virtual DbSet<SellersProduct> SellersProducts { get; set; }
        public virtual DbSet<SendPeriod> SendPeriods { get; set; }
        public virtual DbSet<ServicePrice> ServicePrices { get; set; }
        public virtual DbSet<Service> Services { get; set; }
        public virtual DbSet<Setting> Settings { get; set; }
        public virtual DbSet<Shipping> Shippings { get; set; }
        public virtual DbSet<SizeProduct> SizeProducts { get; set; }
        public virtual DbSet<Size> Sizes { get; set; }
        public virtual DbSet<Slider> Sliders { get; set; }
        public virtual DbSet<SocialMedia> SocialMedias { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<Subscribe> Subscribes { get; set; }
        public virtual DbSet<Tag> Tags { get; set; }
        public virtual DbSet<Template> Templates { get; set; }
        public virtual DbSet<TicketChat> TicketChats { get; set; }
        public virtual DbSet<Ticket> Tickets { get; set; }
        public virtual DbSet<Upload> Uploads { get; set; }
        public virtual DbSet<UserLog> UserLogs { get; set; }
        public virtual DbSet<UserPoint> UserPoints { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UsersAdress> UsersAdresses { get; set; }
        public virtual DbSet<UserSetting> UserSettings { get; set; }
        public virtual DbSet<UserView> UserViews { get; set; }
        public virtual DbSet<VisitStatistic> VisitStatistics { get; set; }
        public virtual DbSet<Wallet> Wallets { get; set; }
        public virtual DbSet<WalletPay> WalletPays { get; set; }
        public virtual DbSet<watchBrand> watchBrands { get; set; }
        public virtual DbSet<WishList> WishLists { get; set; }
        public virtual DbSet<ServiceInquiry> ServiceInquiries { get; set; }
        public virtual DbSet<InquiryManagement> InquiryManagements { get; set; }
    }
}
