//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.UserPoints = new HashSet<UserPoint>();
        }
    
        public int id { get; set; }
        public Nullable<int> userId { get; set; }
        public Nullable<System.DateTime> creationDate { get; set; }
        public Nullable<int> productId { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<int> basketId { get; set; }
        public string status { get; set; }
        public Nullable<int> SellerId { get; set; }
        public Nullable<long> SellerPrice { get; set; }
        public Nullable<long> singleProductPrice { get; set; }
        public Nullable<bool> supply { get; set; }
        public Nullable<System.DateTime> supplyDate { get; set; }
        public Nullable<int> colorId { get; set; }
        public Nullable<int> sizeId { get; set; }
        public string colorSizeDescription { get; set; }
    
        public virtual Basket Basket { get; set; }
        public virtual Product Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserPoint> UserPoints { get; set; }
    }
}
