//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class productView
    {
        public int id { get; set; }
        public Nullable<int> productid { get; set; }
        public Nullable<int> views { get; set; }
        public string token { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
