//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.CatProes = new HashSet<CatPro>();
            this.CommentAdvantages = new HashSet<CommentAdvantage>();
            this.Comments = new HashSet<Comment>();
            this.Discounts = new HashSet<Discount>();
            this.Orders = new HashSet<Order>();
            this.ProductGalleries = new HashSet<ProductGallery>();
            this.ProductPropertiesValues = new HashSet<ProductPropertiesValue>();
            this.ProductQuestions = new HashSet<ProductQuestion>();
            this.ProductRatings = new HashSet<ProductRating>();
            this.ProductTags = new HashSet<ProductTag>();
            this.productViews = new HashSet<productView>();
            this.RattingComments = new HashSet<RattingComment>();
            this.SellersProducts = new HashSet<SellersProduct>();
            this.UserPoints = new HashSet<UserPoint>();
            this.UserViews = new HashSet<UserView>();
            this.WishLists = new HashSet<WishList>();
        }
    
        public int id { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public Nullable<long> price { get; set; }
        public Nullable<int> Inventory { get; set; }
        public string short_description { get; set; }
        public Nullable<bool> ShowOnMainPage { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<int> brandId { get; set; }
        public Nullable<bool> isOriginal { get; set; }
        public Nullable<bool> isAvailable { get; set; }
        public Nullable<int> sellerId { get; set; }
        public Nullable<bool> isValid { get; set; }
        public Nullable<System.DateTime> creationDate { get; set; }
        public Nullable<System.DateTime> submitDate { get; set; }
        public Nullable<bool> editSubmition { get; set; }
        public Nullable<int> point { get; set; }
        public Nullable<int> deliveryDate { get; set; }
        public Nullable<bool> specialSelling { get; set; }
        public string subTitle { get; set; }
        public string MainImage { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<long> priceForSpecialUsers { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatPro> CatProes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommentAdvantage> CommentAdvantages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Discount> Discounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductGallery> ProductGalleries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductPropertiesValue> ProductPropertiesValues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductQuestion> ProductQuestions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductRating> ProductRatings { get; set; }
        public virtual ProductsBrand ProductsBrand { get; set; }
        public virtual ProductsBrand ProductsBrand1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductTag> ProductTags { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<productView> productViews { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RattingComment> RattingComments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SellersProduct> SellersProducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserPoint> UserPoints { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserView> UserViews { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WishList> WishLists { get; set; }
    }
}
