//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductQAnswer
    {
        public int id { get; set; }
        public int QuestionId { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public int UserId { get; set; }
        public string Answer { get; set; }
        public Nullable<bool> IsValidate { get; set; }
    
        public virtual ProductQuestion ProductQuestion { get; set; }
        public virtual User User { get; set; }
    }
}
