//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductGallery
    {
        public int id { get; set; }
        public string big { get; set; }
        public Nullable<int> product_id { get; set; }
        public string small { get; set; }
        public Nullable<int> giftId { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
