//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductQuestion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductQuestion()
        {
            this.ProductQAnswers = new HashSet<ProductQAnswer>();
        }
    
        public int id { get; set; }
        public Nullable<int> ProductId { get; set; }
        public string Question { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<bool> IsValidate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductQAnswer> ProductQAnswers { get; set; }
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
    }
}
