//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Promotion
    {
        public int id { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string bgImage { get; set; }
        public string title { get; set; }
        public Nullable<int> priority { get; set; }
        public string color { get; set; }
    }
}
