//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RattingComment
    {
        public int id { get; set; }
        public Nullable<int> rating { get; set; }
        public Nullable<int> userId { get; set; }
        public Nullable<int> productId { get; set; }
        public Nullable<int> creationDate { get; set; }
        public Nullable<bool> submited { get; set; }
        public Nullable<int> commentId { get; set; }
        public Nullable<int> rattingId { get; set; }
    
        public virtual Comment Comment { get; set; }
        public virtual Product Product { get; set; }
        public virtual Rating Rating1 { get; set; }
        public virtual User User { get; set; }
    }
}
