//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Scan
    {
        public int id { get; set; }
        public string url { get; set; }
        public Nullable<int> userId { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<int> basketId { get; set; }
        public Nullable<int> status { get; set; }
        public string statusString { get; set; }
        public Nullable<bool> isConfirmed { get; set; }
    
        public virtual Basket Basket { get; set; }
        public virtual User User { get; set; }
    }
}
