//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SellersProduct
    {
        public int id { get; set; }
        public Nullable<int> productId { get; set; }
        public Nullable<int> sellerId { get; set; }
        public Nullable<long> price { get; set; }
        public Nullable<bool> isValid { get; set; }
        public Nullable<System.DateTime> creationDate { get; set; }
        public Nullable<System.DateTime> submitDate { get; set; }
        public Nullable<int> Delivery { get; set; }
        public Nullable<bool> isActive { get; set; }
        public string Warranty { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Seller Seller { get; set; }
    }
}
