//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SellerComment
    {
        public int id { get; set; }
        public string name { get; set; }
        public string text { get; set; }
        public Nullable<System.DateTime> creationDate { get; set; }
        public Nullable<int> sellerId { get; set; }
        public Nullable<bool> show { get; set; }
        public Nullable<int> rate { get; set; }
        public Nullable<int> userid { get; set; }
    
        public virtual Seller Seller { get; set; }
        public virtual User User { get; set; }
    }
}
