//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seller
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Seller()
        {
            this.Seller_cats = new HashSet<Seller_cats>();
            this.SellerComments = new HashSet<SellerComment>();
            this.SellersProducts = new HashSet<SellersProduct>();
            this.Tickets = new HashSet<Ticket>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string lastname { get; set; }
        public Nullable<System.DateTime> creationDate { get; set; }
        public string codeMeli { get; set; }
        public string sheba { get; set; }
        public string shomareKart { get; set; }
        public string img { get; set; }
        public Nullable<bool> isValid { get; set; }
        public string token { get; set; }
        public string password { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string easyLogin { get; set; }
        public Nullable<System.DateTime> easyLoginTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Seller_cats> Seller_cats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SellerComment> SellerComments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SellersProduct> SellersProducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ticket> Tickets { get; set; }
    }
}
