//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServicePrice
    {
        public long ServicePriceId { get; set; }
        public long ModelId { get; set; }
        public long ServiceId { get; set; }
        public Nullable<int> Price { get; set; }
    
        public virtual Model Model { get; set; }
        public virtual Service Service { get; set; }
    }
}
