//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceInquiry
    {
        public long UserId { get; set; }
        public Nullable<long> ServicePriceId { get; set; }
        public Nullable<long> Mobile { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
    }
}
