//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shipping
    {
        public int id { get; set; }
        public Nullable<int> ShippingType { get; set; }
        public string ShippingTypeString { get; set; }
        public Nullable<long> ShippingPrice { get; set; }
        public Nullable<int> BasketId { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<int> DeliveryPeriod { get; set; }
    }
}
