//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SizeProduct
    {
        public int id { get; set; }
        public Nullable<int> productId { get; set; }
        public Nullable<int> SizeId { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<long> Price { get; set; }
    }
}
