//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Template
    {
        public int id { get; set; }
        public Nullable<bool> Active { get; set; }
        public string BtnColor { get; set; }
        public string btnHoverColor { get; set; }
        public string BtnTextColor { get; set; }
        public string Title { get; set; }
        public string LinkColor { get; set; }
        public string backgroundShadowInLogin { get; set; }
        public string topLabelColor { get; set; }
        public string labelInProduct { get; set; }
        public string labelUnderMenu { get; set; }
        public string ActiveMenuColor { get; set; }
        public string sliderButtonColor { get; set; }
        public string BasketColorOnMobileMode { get; set; }
        public string labelUnderCategory { get; set; }
        public string BasketLabelColor { get; set; }
        public string AmazingSliderColor { get; set; }
    }
}
