//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketChat
    {
        public int id { get; set; }
        public Nullable<int> ticketId { get; set; }
        public Nullable<bool> isUser { get; set; }
        public Nullable<System.DateTime> creationDate { get; set; }
        public string text { get; set; }
        public string voice { get; set; }
        public Nullable<bool> isSeller { get; set; }
    
        public virtual Ticket Ticket { get; set; }
    }
}
