//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersAdress
    {
        public int id { get; set; }
        public Nullable<int> userId { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> creationDate { get; set; }
        public string postalCode { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<int> City { get; set; }
        public string Location { get; set; }
        public string Reciver { get; set; }
        public string ReciverPhone { get; set; }
    
        public virtual User User { get; set; }
    }
}
