//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Blog_Comments = new HashSet<Blog_Comments>();
            this.Comments = new HashSet<Comment>();
            this.CommnetsLikes = new HashSet<CommnetsLike>();
            this.FalsePasswords = new HashSet<FalsePassword>();
            this.GiftOrders = new HashSet<GiftOrder>();
            this.LogPasswords = new HashSet<LogPassword>();
            this.LogUserAuthenticationDatas = new HashSet<LogUserAuthenticationData>();
            this.LogUserDatas = new HashSet<LogUserData>();
            this.ProductQAnswers = new HashSet<ProductQAnswer>();
            this.ProductQuestions = new HashSet<ProductQuestion>();
            this.RattingComments = new HashSet<RattingComment>();
            this.Scans = new HashSet<Scan>();
            this.SellerComments = new HashSet<SellerComment>();
            this.Tickets = new HashSet<Ticket>();
            this.UserLogs = new HashSet<UserLog>();
            this.UserPoints = new HashSet<UserPoint>();
            this.UserRoles = new HashSet<UserRole>();
            this.UsersAdresses = new HashSet<UsersAdress>();
            this.UserViews = new HashSet<UserView>();
            this.Wallets = new HashSet<Wallet>();
            this.WalletPays = new HashSet<WalletPay>();
            this.WishLists = new HashSet<WishList>();
        }
    
        public int id { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public Nullable<System.DateTime> birth { get; set; }
        public Nullable<bool> gender { get; set; }
        public string image { get; set; }
        public string address { get; set; }
        public string location { get; set; }
        public string token { get; set; }
        public Nullable<bool> mobieVerify { get; set; }
        public string smsToken { get; set; }
        public string mobile { get; set; }
        public string easyLogin { get; set; }
        public Nullable<System.DateTime> easyLoginTime { get; set; }
        public string password { get; set; }
        public string forgetSmsToken { get; set; }
        public Nullable<bool> mobileVerify_forget { get; set; }
        public Nullable<System.DateTime> mobileForgetDateTime { get; set; }
        public string codeMeli { get; set; }
        public string email { get; set; }
        public string card { get; set; }
        public Nullable<int> LoginAttemps { get; set; }
        public string registrationCode { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<System.DateTime> lastOnline { get; set; }
        public Nullable<bool> Special { get; set; }
        public Nullable<bool> RecieveNews { get; set; }
        public Nullable<int> AccessFailedCount { get; set; }
        public Nullable<System.DateTime> LockoutEnd { get; set; }
        public Nullable<bool> IsLock { get; set; }
        public Nullable<bool> IsResetPassword { get; set; }
        public Nullable<System.DateTime> DatePassRefresh { get; set; }
        public string CookieToken { get; set; }
        public string Hostname { get; set; }
        public Nullable<bool> IsEmailConfirm { get; set; }
        public string Username { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Blog_Comments> Blog_Comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommnetsLike> CommnetsLikes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FalsePassword> FalsePasswords { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GiftOrder> GiftOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LogPassword> LogPasswords { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LogUserAuthenticationData> LogUserAuthenticationDatas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LogUserData> LogUserDatas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductQAnswer> ProductQAnswers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductQuestion> ProductQuestions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RattingComment> RattingComments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Scan> Scans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SellerComment> SellerComments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ticket> Tickets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserLog> UserLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserPoint> UserPoints { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserRole> UserRoles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsersAdress> UsersAdresses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserView> UserViews { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Wallet> Wallets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WalletPay> WalletPays { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WishList> WishLists { get; set; }
    }
}
