//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisitStatistic
    {
        public int VisitStatisticsId { get; set; }
        public System.DateTime DateInput { get; set; }
        public string IpAddress { get; set; }
        public string HostName { get; set; }
    }
}
